version: '3.7'
services:
    # Run the node application
    node-app:
        build: .
        container_name: node-app
        restart: unless-stopped
        depends_on:
            - database
        environment:
            NODE_ENV: production
        networks:
            - stack
        env_file: $PWD/.env.prod

    # Run the caddy server
    entrypoint:
        image: caddy/caddy:2.6.2-alpine
        container_name: entrypoint
        restart: unless-stopped
        networks:
            - stack
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/site:/srv
            - caddy_data:/data
            - caddy_config:/config

    # Run the database server
    database:
        image: postgres
        container_name: database
        restart: unless-stopped
        networks:
            - stack
        volumes:
            - database:/var/lib/postgresql/data
            # - /home/debian/Docker/Database:/var/lib/postgresql/data
        env_file: $PWD/.env.prod

networks:
    stack:

volumes:
    caddy_data:
    caddy_config:
    database:
